<script setup>
import { ref, computed, watch } from 'vue'
import { useUserStore } from '@/stores/user'
import { getCoverUrl as getServiceCoverUrl } from '@/services/diving-fish'
import { toPng } from 'html-to-image'
import { Download, Trash2, Image as ImageIcon } from 'lucide-vue-next'

const props = defineProps({
  config: Object,
  cells: Array
})

const emit = defineEmits(['cell-click'])
const userStore = useUserStore()
const canvasRef = ref(null)
const isExporting = ref(false)

const gridCells = computed(() => props.cells)

const getCoverUrl = (song) => {
  if (!song) return null
  return getServiceCoverUrl(song.id)
}

const exportImage = async () => {
  if (!canvasRef.value) return
  isExporting.value = true
  
  try {
    const dataUrl = await toPng(canvasRef.value, {
      cacheBust: true,
      pixelRatio: 2,
      backgroundColor: '#ffffff',
    })
    
    const link = document.createElement('a')
    link.download = `maimai-preference-${new Date().getTime()}.png`
    link.href = dataUrl
    link.click()
  } catch (err) {
    console.error('Export failed:', err)
    alert('导出图片失败，请重试')
  } finally {
    isExporting.value = false
  }
}

// Theme classes map
const themeClasses = computed(() => {
  const map = {
    default: 'bg-white',
    dark: 'bg-gray-900 text-white',
    pink: 'bg-pink-50',
    blue: 'bg-blue-50'
  }
  return map[props.config.theme] || 'bg-white'
})

const textClasses = computed(() => {
  return props.config.theme === 'dark' ? 'text-white' : 'text-black'
})

const borderClasses = computed(() => {
  return props.config.theme === 'dark' ? 'border-white' : 'border-black'
})

</script>

<template>
  <div class="flex flex-col items-center gap-4">
    <!-- Toolbar -->
    <div class="flex gap-2 w-full justify-end">
      <button 
        @click="exportImage" 
        :disabled="isExporting"
        class="btn-base bg-maimai-green text-white flex items-center gap-2"
      >
        <Download :size="18" />
        {{ isExporting ? '生成中...' : '保存图片' }}
      </button>
    </div>

    <!-- Canvas Container -->
    <div class="border-2 border-black shadow-hard bg-gray-50 p-4 rounded-xl">
      <div 
        ref="canvasRef"
        class="w-[800px] aspect-[3/4] p-8 flex flex-col relative transition-colors duration-300"
        :class="themeClasses"
      >
        <!-- Header -->
        <div class="flex justify-between items-start mb-8 border-b-4 pb-4" :class="borderClasses">
          <div>
            <h1 class="text-4xl font-black tracking-tighter mb-2 whitespace-nowrap" :class="textClasses">{{ config.title || 'Maimai歌曲喜好表' }}</h1>
            <div class="text-sm opacity-60 font-bold" :class="textClasses">GENERATED BY MAIMAI TOOLS</div>
          </div>
          <div class="flex flex-col items-end gap-1">
            <div class="text-2xl font-bold" :class="textClasses">
              {{ userStore.profile.nickname || 'Player Name' }}
            </div>
            <div class="text-xl font-mono font-bold text-maimai-yellow drop-shadow-sm bg-black px-4 py-2 rounded-lg leading-normal">
              RATING: {{ userStore.profile.rating || '00000' }}
            </div>
          </div>
        </div>

        <!-- Grid -->
        <div class="flex-1 grid grid-cols-3 grid-rows-4 gap-6">
          <div 
            v-for="(cell, index) in gridCells" 
            :key="index"
            class="relative flex flex-col h-full group cursor-pointer"
            @click="$emit('cell-click', index)"
          >
            <!-- Card Frame -->
            <div 
              class="flex-1 border-2 rounded-xl overflow-hidden relative bg-gray-100 transition-all hover:shadow-hard-sm"
              :class="[borderClasses, !cell.song ? 'hover:bg-gray-200' : '']"
            >
              <!-- Placeholder -->
              <div v-if="!cell.song" class="absolute inset-0 flex items-center justify-center opacity-20">
                <ImageIcon :size="48" :class="textClasses" />
              </div>

              <!-- Song Cover -->
              <img 
                v-if="cell.song" 
                :src="getCoverUrl(cell.song)" 
                class="absolute inset-0 w-full h-full object-cover"
                crossorigin="anonymous"
                referrerpolicy="no-referrer"
              />
              
              <!-- Song Info Overlay (Bottom) -->
              <div v-if="cell.song" class="absolute bottom-0 left-0 right-0 bg-black/80 px-3 py-3 text-white">
                <div class="font-bold text-sm truncate mb-1">{{ cell.song.title }}</div>
                <div class="flex justify-between items-center">
                  <div class="text-[10px] opacity-80 truncate max-w-[60%] leading-normal">{{ cell.song.basic_info.artist }}</div>
                  <div v-if="cell.song.record" class="text-xs font-mono text-maimai-yellow font-bold leading-normal">
                    {{ cell.song.record.achievements.toFixed(4) }}%
                  </div>
                </div>
              </div>
            </div>

            <!-- Label -->
            <div class="mt-2 text-center font-bold text-lg" :class="textClasses">
              {{ cell.label }}
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="mt-4 text-center text-xs font-bold opacity-40" :class="textClasses">
          Created with Maimai Tools
        </div>
      </div>
    </div>
  </div>
</template>
