<script setup>
import { getCoverUrl } from '@/services/diving-fish'
import { Star, Quote } from 'lucide-vue-next'

const props = defineProps({
  reviews: {
    type: Array,
    required: true
  },
  username: {
    type: String,
    default: 'PLAYER'
  }
})

const getQualityLabel = (val) => {
    const map = { 5: '神谱', 4: '好谱', 3: '一般', 2: '有点拉', 1: '依托答辩' }
    return map[val] || ''
}

const getQualityEmoji = (val) => {
    const map = { 5: '🔥', 4: '👍', 3: '😐', 2: '👎', 1: '💩' }
    return map[val] || ''
}

const getQualityColor = (val) => {
    const map = { 5: 'bg-red-500', 4: 'bg-orange-400', 3: 'bg-yellow-400', 2: 'bg-blue-400', 1: 'bg-gray-600' }
    return map[val] || 'bg-black'
}
</script>

<template>
  <div class="bg-[#F5F5F5] p-8 w-[600px] min-h-[800px] flex flex-col gap-6">
    <!-- Header -->
    <div class="bg-white border-2 border-black p-4 rounded-xl shadow-[4px_4px_0px_0px_#000000] flex items-center justify-between">
        <div class="flex items-center gap-3">
            <div class="w-10 h-10 bg-maimai-blue rounded-full border-2 border-black flex items-center justify-center text-white font-black">
                {{ username.charAt(0).toUpperCase() }}
            </div>
            <div>
                <div class="font-black text-lg leading-none">Maimai 谱面锐评</div>
                <div class="text-xs font-bold text-gray-500 mt-1">{{ new Date().toLocaleDateString() }}</div>
            </div>
        </div>
        <div class="px-3 py-1 bg-black text-white font-black text-sm rounded-full">
            {{ reviews.length }} Songs
        </div>
    </div>

    <!-- Cards -->
    <div class="space-y-6">
        <div v-for="review in reviews" :key="review.id" class="bg-white border-2 border-black rounded-2xl overflow-hidden shadow-[6px_6px_0px_0px_#000000]">
            <!-- Top: Cover & Basic Info -->
            <div class="flex h-32 border-b-2 border-black">
                <div class="w-32 h-32 flex-shrink-0 border-r-2 border-black relative">
                    <img :src="getCoverUrl(review.songId)" class="w-full h-full object-cover" crossorigin="anonymous" />
                    <div class="absolute top-0 left-0 bg-black text-white text-[10px] font-bold px-1.5 py-0.5 rounded-br">
                        {{ review.type }}
                    </div>
                </div>
                <div class="flex-1 p-3 flex flex-col justify-between bg-white relative overflow-hidden">
                    <!-- Background decoration -->
                    <div class="absolute -right-4 -bottom-4 text-9xl opacity-5 select-none pointer-events-none">
                        {{ getQualityEmoji(review.qualityRating) }}
                    </div>

                    <div>
                        <h3 class="font-black text-lg leading-tight line-clamp-2 mb-1">{{ review.title }}</h3>
                        <div class="text-xs font-bold text-gray-500">{{ review.level }}</div>
                    </div>

                    <div class="flex items-center gap-3 relative z-10">
                        <!-- Star Rating -->
                        <div class="flex gap-0.5">
                            <Star v-for="i in 5" :key="i" :size="16" 
                                :class="i <= review.starRating ? 'fill-maimai-yellow text-maimai-yellow' : 'text-gray-200'" 
                                stroke-width="3"
                            />
                        </div>
                        <!-- Quality Badge -->
                        <div :class="['px-2 py-0.5 text-xs font-black text-white rounded-md border border-black shadow-[1px_1px_0px_0px_#000000]', getQualityColor(review.qualityRating)]">
                            {{ getQualityLabel(review.qualityRating) }}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Bottom: Comment -->
            <div class="p-4 bg-gray-50 relative">
                <Quote :size="24" class="text-gray-300 absolute top-2 left-2" />
                <div class="relative z-10 pl-6">
                    <div class="font-black text-lg text-gray-800 leading-tight mb-1">
                        {{ review.oneLiner }}
                    </div>
                    <div v-if="review.comment" class="text-xs text-gray-500 font-medium mt-2 border-t border-gray-200 pt-2">
                        {{ review.comment }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="mt-auto text-center">
        <div class="inline-block px-4 py-1 bg-black text-white text-xs font-bold rounded-full">
            Generated by Maimai Tools
        </div>
    </div>
  </div>
</template>
