<script setup>
import { getCoverUrl } from '@/services/diving-fish'
import RatingInput from '../RatingInput.vue'

const props = defineProps({
  reviews: {
    type: Array,
    required: true
  },
  username: {
    type: String,
    default: 'PLAYER'
  }
})

const getQualityLabel = (val) => {
    const map = { 5: '🔥 夯', 4: '👍 好谱', 3: '😐 一般', 2: '👎 有点拉', 1: '💩 依托答辩' }
    return map[val] || ''
}

const getQualityColor = (val) => {
    const map = { 5: 'text-red-600', 4: 'text-orange-500', 3: 'text-yellow-600', 2: 'text-blue-500', 1: 'text-gray-600' }
    return map[val] || 'text-black'
}
</script>

<template>
  <div class="bg-white p-8 w-[800px] min-h-[600px]">
    <!-- Header -->
    <div class="flex items-center justify-between mb-6 border-b-4 border-black pb-4">
        <div>
            <h1 class="text-3xl font-black tracking-tighter">MAIMAI 谱面评价表</h1>
            <div class="text-gray-500 font-bold mt-1">Review by {{ username }}</div>
        </div>
        <div class="text-right">
            <div class="text-sm font-bold text-gray-400">Generated by</div>
            <div class="text-xl font-black">Maimai Tools</div>
        </div>
    </div>

    <!-- Table -->
    <div class="border-2 border-black">
        <!-- Table Header -->
        <div class="grid grid-cols-[80px_1fr_140px_1fr] bg-black text-white font-black text-sm">
            <div class="p-2 text-center">封面</div>
            <div class="p-2">曲名 / 难度</div>
            <div class="p-2">评分</div>
            <div class="p-2">一句话评价</div>
        </div>

        <!-- Rows -->
        <div v-for="(review, index) in reviews" :key="review.id" 
             :class="['grid grid-cols-[80px_1fr_140px_1fr] border-b border-black last:border-b-0', index % 2 === 0 ? 'bg-white' : 'bg-gray-50']">
            
            <!-- Cover -->
            <div class="p-2 flex items-center justify-center border-r border-black">
                <img :src="getCoverUrl(review.songId)" class="w-14 h-14 object-cover border border-black" crossorigin="anonymous" />
            </div>

            <!-- Info -->
            <div class="p-2 flex flex-col justify-center border-r border-black min-w-0">
                <div class="font-bold text-sm truncate leading-tight mb-1">{{ review.title }}</div>
                <div class="flex items-center gap-2">
                    <span class="text-[10px] font-black px-1.5 py-0.5 bg-gray-200 rounded border border-gray-400">{{ review.type }}</span>
                    <span class="text-xs font-bold text-gray-600">{{ review.level }}</span>
                </div>
            </div>

            <!-- Rating -->
            <div class="p-2 flex flex-col justify-center border-r border-black">
                <RatingInput :model-value="review.starRating" :max="5" readonly class="scale-75 origin-left mb-1" />
                <div :class="['text-xs font-black', getQualityColor(review.qualityRating)]">
                    {{ getQualityLabel(review.qualityRating) }}
                </div>
            </div>

            <!-- Comment -->
            <div class="p-2 flex items-center font-medium text-sm text-gray-800">
                {{ review.oneLiner }}
            </div>
        </div>
    </div>
    
    <!-- Footer -->
    <div class="mt-4 text-center text-gray-400 text-xs font-bold">
        Create your own at maimai-tools.vercel.app
    </div>
  </div>
</template>
